### ISSUE TITLE
iOS icon for home screen web app

### ISSUE THREAD

**Issue by sman591** [brandonhudson/CSHMovies#6]
This website goes great as a website saved to the home screen. However, the icon isn't so great:

![img_4491](https://cloud.githubusercontent.com/assets/1441807/12077124/46e7f88c-b19f-11e5-91d8-f1aa84e8c7b6.jpg)

Simply optimizing the homepage logo to be centered & enlarged could work, or you could try to match the style of the Plex logo with something.

**Comment by brandonhudson** [comment]
It has an icon with a white background and purple logo (looks similar to YouTube). It was working there for a while but I'm guessing the issue arises when it was moved behind webauth and the asset can't be accessed unless you're authed in. I'll move the icons to my public html pages and see if that fixes it.

**Comment by brandonhudson** [comment]
Fixed 01/03/16

**Comment by sman591** [comment]
:+1:
